### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by moodledan** [magbicaleman/open-in-browser#10]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/dan/.atom/packages/open-in-browser/lib/open-in-browser.coffee:7:9)
```

**Comment by magbicaleman** [comment]
Hey, I just updated to v0.4.2 give that an update and let me know if you're still getting the error. Thank you.

**Comment by pringshia** [comment]
@magbicaleman I'm still getting this warning on v0.4.2

**Comment by magbicaleman** [comment]
@pringshia I've updated to v0.4.3 are you still getting same error?

**Comment by pringshia** [comment]
@magbicaleman Nope, no more warnings. Thanks.
