### ISSUE TITLE
not revealing in browser

### ISSUE THREAD

**Issue by seanlarge** [magbicaleman/open-in-browser#11]
I just installed atom and I am working from a windows 7 os. ctrl alt q does not seem to be working for me neither does right click..

**Comment by oleic** [comment]
Same issue.

**Comment by anderson-arlen** [comment]
+1 on Linux Mint

**Comment by sometxdude** [comment]
Same on OS X

**Comment by anderson-arlen** [comment]
It works now, perhaps I needed to reload the editor after installing.

**Comment by magbicaleman** [comment]
Anyone else still having this issue?

**Comment by sometxdude** [comment]
Still having the issue.  This time on Linux Mint with atom 0.187.

**Comment by magbicaleman** [comment]
@sometxdude if your default browser is Chrome, it might be a Chrome issue check this thread out: https://github.com/magbicaleman/open-in-browser/issues/1

**Comment by knieber** [comment]
Hi, this isn't working for either, even if I use Safari as my default broswer.

**Comment by magbicaleman** [comment]
@knieber is this still an issue, and what OS are you on?

**Comment by knieber** [comment]
@magicaleman I actually saw some deprecation notes and it told me to change the "stylesheet" folder to "styles" within the package. Now it works!

**Comment by magbicaleman** [comment]
@knieber @seanlarge @sometxdude @oleic  Just release v0.4.6 this should fix many of the issues here. If you have any more issues or issues are not resolved please make a new issue. Thank you.
