### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by Byronvis** [magbicaleman/open-in-browser#15]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `open-in-browser` package
```
Package.getStylesheetsPath (/opt/atom/resources/app/src/package.js:433:9)
Package.getStylesheetPaths (/opt/atom/resources/app/src/package.js:444:32)
```

**Comment by magbicaleman** [comment]
This should be fixed by the following commit: 9bfbb5a053dc028cda4f860c1b7c090a4354f97d
