### ISSUE TITLE
Does nothing on my machine

### ISSUE THREAD

**Issue by amadeusp** [magbicaleman/open-in-browser#22]
Hi there

On my OS X 10.10.4 (14E46) machine nothing happens, when I trigger the open in browser command. It doesn't matter if I try to fire it with the cmd+shift+p+Open in Browser: Open or via right-click. Also, I cannot see anything in Console.app. Am I missing something?

All the best!

Amadeus

**Comment by nfroidure** [comment]
Same here on Debian GNU/Linux

**Comment by magbicaleman** [comment]
Do you guys have any plugin that could be taking that over? My apologies for the later reply.

**Comment by nfroidure** [comment]
I'm not sure but it is probably not due to this module since i assume it uses the open command and it seems broken on my system.

**Comment by slipsback** [comment]
same problem on a pc
