### ISSUE TITLE
open-in-browser not working

### ISSUE THREAD

**Issue by michaelmena** [magbicaleman/open-in-browser#23]
Hi

thanks for building this add-on. However, its not working for me.

**Comment by magbicaleman** [comment]
@michaelmena Thanks, do you have any console errors. If you go to your terminal and type "open ./" does that do anything for you (assuming you're on linux/mac). If you're on windows, what version are you running?

**Comment by qiaocuixinzhiweini** [comment]
my window version is 8.1,it's not work yet!

**Comment by magbicaleman** [comment]
@qiaocuixinzhiweini , I do not have a way to test on windows. :(

**Comment by joshvickerson** [comment]
It doesn't work for me either, using Atom 1.0.19 on Mac OS X 10.11.1. No console errors.

My default browser is Safari 9, not sure if it's just failing to identify that?

**Comment by Pbryanw** [comment]
Hi, I've noticed that if you set .html files in OS X, to open with a text editor, then Atom won't be able to use this community package. You have to set the html filetype to open with either Chrome, Firefox or Safari depending on your preference. You can set the default browser you want your .html files to open in, by changing the associated browser these files open with. I only use Atom on OS X, so don't know if the same is true for Windows.

**Comment by keeper0811** [comment]
not working on Window 7
Atom 1.4.1
Chrome 48.0.2564.97

**Comment by chinkara** [comment]
Also not working on Windows 7 & Atom 1.4.1. Is there a way to change the shortcut keys? Right clicking and then selecting "open in browser" is not the method I prefer.
All of the posts from this thread are old. Has there been any resolution to this issue? Thanks
