### ISSUE TITLE
Localhost

### ISSUE THREAD

**Issue by dmase44** [magbicaleman/open-in-browser#24]
The open in browser opens from the file list. How can it be set to open as the localhost on my dev server.?

**Comment by magbicaleman** [comment]
@dmase44 there currently isn't one, this is something I did want to add as a feature.

**Comment by dmase44** [comment]
Thanks for the reply. I do hope this feature comes soon as browsers really choke refreshing through the file tree.

**Comment by magbicaleman** [comment]
@dmase44 do you use a project manager plugin? I'm trying to avoid a strong dependency to another package, but at the same time, don't want to create an alternative package.

**Comment by dmase44** [comment]
No I don’t use a project manager plugin. I have another browser package I’m using now, atom-live-server that does use localhost.

 

Thanks for your time, Dave
