### ISSUE TITLE
Does not opens file...

### ISSUE THREAD

**Issue by nnukem** [magbicaleman/open-in-browser#28]

**Comment by gbouvyer** [comment]
Same here. ctrl-alt-q doesn't do anything.

**Comment by laoqiren** [comment]
me too,I'm very disappointed by this issue,I want to give up atom

**Comment by Machars** [comment]
插件的快捷键打开依赖node的gui模块，因为我的系统不支持gui模块，所以用“ctrl+alt+q”是打不开，但是"ctrl+."是可以看到快捷键运行的，所以我判定是依赖的模块不工作，我看了一下插件远吗，发现打开.html文件的代码是shell.openExternal("file://"+filePath)，然后又找了这个函数在那个函数库，发现是node的gui模块，然后我发现我并没有这个模块，所以尝试安装了下，发现系统不支持（我的系统是window server2008 r2）我觉得应该是这个问题，仅供参考
ps:别怪我奇葩，因为我的英文只能看懂，完全不知道怎么翻译上面那段文字，所以只能希望你能看懂
