### ISSUE TITLE
Not compatible with nuclide-file-tree :(

### ISSUE THREAD

**Issue by aiboy** [magbicaleman/open-in-browser#29]
Steps to reproduce.. 

1) install Nuclide
2) install open-in-browser
3) Click on treeView - doesn't work

PS: probably because Nuclide uses nuclide-file-tree instead of file-tree. Plz fix asap

**Comment by aiboy** [comment]
Is there anything I could help. Would you accept pull request?

**Comment by magbicaleman** [comment]
@aiboy yea, feel freel.

**Comment by aiboy** [comment]
Created pull request
https://github.com/magbicaleman/open-in-browser/pull/30

**Comment by magbicaleman** [comment]
Merged and published
