### ISSUE TITLE
it opens the php on visual studio

### ISSUE THREAD

**Issue by chalaco** [magbicaleman/open-in-browser#36]
When I click on open on browser, it opens the page on visual studio.  I'm trying to change the configuration but i cannot find it where to do this.

**Comment by betsylambright** [comment]
Mine opens up Dreamweaver... I'm also trying to figure out how to change that.

**Comment by magbicaleman** [comment]
This is an operating system preference setting. For example if you're working on a `.js` file, make sure to select the correct application you want the `.js` file to open. Behind the scenes the plugin, just uses your operating systems, default open with preference.
