### ISSUE TITLE
Keybind not working

### ISSUE THREAD

**Issue by aglome** [magbicaleman/open-in-browser#41]
After update, Ctrl + Alt + Q won't open in my default browser.
The Keybindings tab's "Enable" button is ticked.

 
> Keystroke	Command	Selector	Source
> ctrl-shift-Q	open-in-browser:open	.platform-win32 atom-workspace atom-text-editor	Open In > Browser

**Comment by magbicaleman** [comment]
It no longer binds to ALT but to SHIFT, sorry for the inconvenience. 

```
'.platform-win32 atom-workspace atom-text-editor':
  'ctrl-shift-q': 'open-in-browser:open'

'.platform-linux atom-workspace atom-text-editor':
  'ctrl-shift-q': 'open-in-browser:open'

'.platform-darwin atom-workspace atom-text-editor':
  'cmd-shift-q': 'open-in-browser:open'
```
