### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jpietrangelo** [magbicaleman/open-in-browser#6]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/jmp/.atom/packages/open-in-browser/lib/open-in-browser.coffee:8:9)
```

**Comment by magbicaleman** [comment]
@jpietrangelo I just updated the package this should be working now. https://github.com/magbicaleman/open-in-browser/commit/422db025e9db610ecb3e8392dd72b59cbf6b187b
