### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jpietrangelo** [magbicaleman/open-in-browser#7]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.activate (/Users/jmp/.atom/packages/open-in-browser/lib/open-in-browser.coffee:7:9)
```

**Comment by magbicaleman** [comment]
Hey, I just updated to v0.4.2 give that an update and let me know if you're still getting the error. Thank you.

**Comment by pringshia** [comment]
I'm still getting this warning in Atom and am on v0.4.2.
