### ISSUE TITLE
"Open in Browser" in Tree View Doesn't Work at First (Windows)

### ISSUE THREAD

**Issue by loganfranken** [magbicaleman/open-in-browser#8]
(Thanks for putting together this awesome package!)

I run Windows 7 and I ran into a really strange bug with this package (or possibly with Atom itself):

If I open Atom and then try to right-click a file from the tree view and "Open in Browser," it doesn't do anything. No errors or anything.

However, if I first "Open in Browser" via right-clicking within a *file*, both the tree view and file view options will start working after that.

Looking in  the Developer Tools, it looks like this occurs because the "open-in-browser" package is only requested by Atom *after* executing "Open in Browser" within a *file*. I've been unable to figure out why this happens, though.

**Comment by magbicaleman** [comment]
Hey, I just updated to v0.4.2 give that an update and let me know if you're still getting the error. Thank you.

**Comment by loganfranken** [comment]
Augh, sorry: I tried the update: it still doesn't work for me.

I'm almost thinking it's either an error specific to my machine or an error with Atom. From everything I could see in their documentation, your package **should** be getting brought in upon trying to open from the tree view. I'm not sure why it doesn't.

I think I should try creating a simple Atom package to recreate the problem outside your package to see if it really has anything to do with your package or not.

If you also feel like it's more of an issue with Atom or my environment, please feel free to close the ticket. I'll reopen if I discover anything new.

**Comment by magbicaleman** [comment]
Are you still seeing this in version 0.4.3?

**Comment by loganfranken** [comment]
Yeah, unfortunately, I still am

**Comment by magbicaleman** [comment]
@loganfranken version 0.4.6 just released of this package. I believe the right pane issue should be fixed.

**Comment by loganfranken** [comment]
*Holy crap!* It's fixed! You're amazing; thank you so much!
